# Project Information
site_name: RainPPR's Blog
site_description: by RainPPR
site_author: RainPPR
strict: false

site_url: https://rainppr.github.io/
repo_name: RainPPR/rainppr.github.io

repo_url: https://github.com/RainPPR/rainppr.github.io
edit_uri: blob/master/project/docs/
# copyright: Copyright &copy; 2016 - 2023 CTF Wiki Team

# Theme
theme:
    name: material
    language: 'zh'
    palette:
        primary: white
        accent: red
        scheme: preference
    icon:
        repo: fontawesome/brands/github-alt
   # logo: static/img/logo.png
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
        - search.share
        - content.action.edit
    include_search_page: false
    search_index_only: true
    font:
        code: 'Fira Code'
        text: 'Noto Sans'

plugins:
- search
- minify:
    minify_html: true

nav:
    - 简介:
        - index.md
        - usage.md
        - discussion.md
    - 开始:
        - start/hello.md
# - Introduction:
#     - introduction/history.md
#     - introduction/mode.md
#     - introduction/content.md
#     - introduction/experience.md
#     - introduction/cgc.md
#     - introduction/resources.md

# Customization
extra:
    disqus: 'RainPPR'
    pagetime: 'on'
    manifest: 'manifest.webmanifest'

extra_javascript:
    - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
    - static/js/extra.js
    - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
    - static/css/extra.css
    #- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/normalize-opentype.css/0.2.4/normalize-opentype.min.css

# Extensions
markdown_extensions:
    - md_in_html
    - admonition
    - def_list
    - footnotes
    - meta
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
#        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg

    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols

    - pymdownx.snippets:
        check_paths: true
    - pymdownx.progressbar
    - pymdownx.superfences:
        custom_fences:
        # - name: math
        #     class: arithmatex
        #     format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true
